# Generated by Django 5.0 on 2023-12-30 10:02

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EventCatogry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('max_number_of_participant', models.IntegerField()),
                ('event_location', models.CharField(max_length=255)),
                ('event_discription', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('event_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('event_catogry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_1.eventcatogry')),
            ],
        ),
        migrations.CreateModel(
            name='Partecipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partecipant_first_name', models.TextField(max_length=255)),
                ('partecipant_last_name', models.TextField(max_length=255)),
                ('partecipant_email', models.EmailField(max_length=254)),
                ('partecipant_phone', models.IntegerField()),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_1.event')),
            ],
        ),
    ]
