# Generated by Django 5.0 on 2023-12-30 10:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='partecipant',
            name='partecipant_pict',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='photos/%y/%m/%d'),
            preserve_default=False,
        ),
    ]
