# Generated by Django 5.0 on 2024-01-12 11:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0002_partecipant_partecipant_pict'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['name'], 'verbose_name': 'Event'},
        ),
        migrations.AlterField(
            model_name='partecipant',
            name='partecipant_first_name',
            field=models.TextField(max_length=20),
        ),
        migrations.AlterField(
            model_name='partecipant',
            name='partecipant_last_name',
            field=models.TextField(max_length=20),
        ),
        migrations.CreateModel(
            name='Sinup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partecipant_first_name', models.TextField(max_length=20)),
                ('partecipant_last_name', models.TextField(max_length=20)),
                ('partecipant_pict', models.ImageField(upload_to='photos/%y/%m/%d')),
                ('partecipant_email', models.EmailField(max_length=254)),
                ('partecipant_phone', models.IntegerField()),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_1.event')),
            ],
        ),
    ]
