# Generated by Django 5.0 on 2024-01-13 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0004_alter_sinup_partecipant_first_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='is_active',
        ),
    ]
